### ISSUE TITLE
Get Mobile number VPA issuers

### ISSUE THREAD

**Issue by srikanthlogic** [qurbat/upi-recon#8]
Filter All VPA issuers to those who issue mobile number based VPAs after validation

**Comment by qurbat** [comment]
I think documentation published by NPCI would be a good place to start.

**Comment by srikanthlogic** [comment]
I think - we can only have a negative list - replicate the suffix list and exclude known suffixes that are for special purpose / used in apps that don't allow mobile based VPAs (GPay, Whatsapp Pay)

**Comment by qurbat** [comment]
This makes sense, though I'll spend some time exploring explore what the best way of implementing such a list type might look like. Thank you @srikanthlogic 🙂
