### ISSUE TITLE
Get list of FASTag issuers

### ISSUE THREAD

**Issue by srikanthlogic** [qurbat/upi-recon#9]
Get VPA suffixes of all FASTag issuers.

- [NPCI Issuer list](https://www.npci.org.in/what-we-do/netc-fastag/live-members) - [UPI Handles](https://www.npci.org.in/PDF/npci/netc/Bank-UPI-Handels.pdf)
- [FASTag recharges using BHIM](https://www.bankbazaar.com/driving-licence/fastag-recharge-through-bhim-upi.html)

**Comment by qurbat** [comment]
#11 addresses this and is pending review.
